### ISSUE TITLE
Outros e-commerces?

### ISSUE THREAD

**Issue by danielpcamara** [felipe2g/e-commerce-price-checker#4]
Olá Felipe tudo bom? Muito obrigado por compartilhar essa API.
Poderia me dizer como chegou à ela? Gostaria de encontrar outras APIs de sites como Terabyteshop e Pichau. Você poderia me apontar a direção para encontrar uma URL similar à listada abaixo?
`https://servicespub.prod.api.aws.grupokabum.com.br/descricao/v1/descricao/produto/${productId}`

**Comment by felipe2g** [comment]
Olá Daniel, tudo ótimo e você?

Eu cheguei a ela analisando os javascripts pelo google dev.

Para encontrar você vai ter que interceptar o script que realiza a chamada
a API das lojas.

Posso tentar mais tarde te auxiliar.

Caso queira entre em contato no meu discord. 2gfelipe#6311

Em ter., 21 de abr. de 2020 às 17:41, danielpcamara <
notifications@github.com> escreveu:

**Comment by felipe2g** [comment]
@danielpcamara dei inicio ao desenvolvimento da terabyte shop, atualmente já está sendo puxado todos os detalhes do produto em si, exceto o seu preço parcelado.
