### ISSUE TITLE
Em terabyteshop, a response.status esta retornando 201

### ISSUE THREAD

**Issue by thiagopaesm** [felipe2g/e-commerce-price-checker#6]
Olá Felipe tudo bom? Parabéns pelo trabalho. Estou com um problema ao consultar um produto da terabyte. O resultado da requisição é 201. Você sabe o que está acontecendo?

Abraço,

**Comment by felipe2g** [comment]
Infelizmente a Terabyteshop implementou um sistema anti DDoS na plataforma deles, o Cloud Flare. Que está barrando as requisições do projeto. Daí tem de ser estudado algo pra passar por isso, vou desabilitar as rotas no próximo commit e propor uma solução pra isso, por hora.

Abraço!

**Comment by felipe2g** [comment]
@thiagopaesm achei em um blog israelense que conseguiu dar um bypass na cloudflare com o Selenium em Python, acredito que fazendo o scrap com o Selenium no Node poderemos ter sucesso também.

http://www.korznikov.com/2015/05/simple-cloudflare-bypass.html

No caso do python ele instanciou o Selenium, aguardou por 10 segundos na página, para que ele carregue a primeira vez recebendo os cookies do Cloud Flare, pegou os cookies com o Cookie Jar, e na próxima vez que instanciou levou estes cookies pra requisição. Tentarei fazer algo deste tipo.

Abaixo segue o código de exemplo em Python.

`
#!/usr/bin/python

from selenium import webdriver
from time import sleep
import cookielib
import requests

print 'Launching Firefox..'
browser = webdriver.Firefox()
print 'Entering to skidpaste.org...'
browser.get('http://skidpaste.org')
print 'Waiting 10 seconds...'
sleep(10)
a = browser.get_cookies()
print 'Got cloudflare cookies:\n'
print 'Closing Firefox..'
browser.close()

h = {'User-Agent': 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:35.0) Gecko/20100101 Firefox/35.0'}

b = cookielib.CookieJar()

for i in a:
  ck = cookielib.Cookie(name=i['name'], value=i['value'], domain=i['domain'], path=i['path'], secure=i['secure'], rest=False, version=0,port=None,port_specified=False,domain_specified=False,domain_initial_dot=False,path_specified=True,expires=i['expiry'],discard=True,comment=None,comment_url=None,rfc2109=False)
  b.set_cookie(ck)

r = requests.get('http://skidpaste.org', cookies=b, headers=h)
print len(r.content)
print r.status_code
`
